### ISSUE TITLE
i have an issue

### ISSUE THREAD

**Issue by Shinpi-Tekita** [MrPotato30/spudjs-docs#1]
so I want to steal your source code https://spud.js.org/ for the pages but I can't do ctrl + u on it please help not a troll

**Comment by MrPotato30** [comment]
Why would you want to steal the source code from our website?

**Comment by Shinpi-Tekita** [comment]
> Why would you want to steal the source code from our website?

**Comment by Shinpi-Tekita** [comment]
HMMMMMMMM
