### ISSUE TITLE
add new docs

### ISSUE THREAD

**Issue by Shinpi-Tekita** [MrPotato30/spudjs-docs#2]
add the new features of the package and add the package in the packages section

**Comment by MrPotato30** [comment]
Hi Shinpi-Tekita, 👋
thank you for reaching out to us!

We'll work on the documentation as soon as possible. Could you please explain what you mean by "add the package in the packages section"? We'd appreciate it if you could make recommendations/suggestions and feedback on the Discord server.

Looking forward to your reply!
- mrpotato30 😀

**Comment by Shinpi-Tekita** [comment]
> 

Potato what i meant in the page about theres a section where it says packages can u add the package in that section and can u add the new docs for the newest version of the package :)

**Comment by Shinpi-Tekita** [comment]
where new docs ?
